title: St. Invicta's Primary School
description: St. Invicta's is a primary school in Eastbourne, East Sussex.
permalink: pretty
lang: en_GB
timezone: Europe/London

url:

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy
  - jekyll-algolia

algolia:
  application_id: 'GS6YCBDMKW'
  index_name: 'st_invictas'
  files_to_exclude:
    - ./_alerts/*

uploads_dir: "/assets/media/:title"

# incremental: true

collections:
  alerts:
    _hide_content: false
    output: true
    _icon: warning
  curriculum:
    _hide_content: false
    output: true
    _icon: menu_book
    permalink: /school-life/curriculum/:title/
    _add_options:
      - name: Add standard page
        icon: web
        href: "cloudcannon:explore/_curriculum/.md🆕/_templates/_standard-page.md"
      - name: Add gallery page
        icon: photo_album
        href: "cloudcannon:explore/_curriculum/.md🆕/_templates/_gallery-page.md"
  school-information:
    _hide_content: false
    output: true
    _icon: info
    permalink: /school-information/:title/
  school-life:
    _hide_content: false
    output: true
    _icon: school
    permalink: /school-life/:title/
  send:
    _hide_content: false
    output: true
    _icon: escalator_warning
    permalink: /send/:title/
  staff:
    _hide_content: false
    output: true
    _icon: groups
    permalink: /staff/:title/
  policies:
    _hide_content: false
    output: true
    _icon: description
    permalink: /policies/:title/
  posts:
    _enabled_editors:
      - content
      - visual
    output: true
    permalink: /news/:year/:month/:day/:title/

_options:

  layout:
    hidden: true
  _block:
    height: 500
    width: 800
    resize_style: "cover"
    format: p h3 h4 h5
    bold: true
    italic: true
    removeformat: true
    link: true
    underline: true
    blockquote: true
    bulletedlist: true
    numberedlist: true
    table: true
    left: text-left
    center: text-center
    right: text-right
    justify: false
    styles: /_sass/cms_styles.css
    embed: true
    undo: true
    redo: true
    image: true
  content:
    height: 500
    width: 800
    resize_style: "cover"
    format: p h3 h4 h5
    bold: true
    italic: true
    removeformat: true
    link: true
    underline: true
    blockquote: true
    bulletedlist: true
    numberedlist: true
    table: true
    left: text-left
    center: text-center
    right: text-right
    justify: false
    styles: /_sass/cms_styles.css
    embed: true
    undo: true
    redo: true
    image: true
  content_markdown:
    height: 500
    width: 800
    resize_style: "cover"
    format: p h3 h4 h5
    bold: true
    italic: true
    removeformat: true
    link: true
    underline: true
    blockquote: true
    bulletedlist: true
    numberedlist: true
    table: true
    left: text-left
    center: text-center
    right: text-right
    justify: false
    styles: /_sass/cms_styles.css
    embed: true
    undo: true
    redo: true
    image: true
  introduction_markdown:
    height: 500
    width: 800
    resize_style: "cover"
    format: p h3 h4 h5
    bold: true
    italic: true
    removeformat: true
    link: true
    underline: true
    blockquote: true
    bulletedlist: true
    numberedlist: true
    table: false
    left: text-left
    center: text-center
    right: text-right
    justify: false
    styles: /_sass/cms_styles.css
    embed: false
    undo: true
    redo: true
    image: false

_array_structures:
  gallery:
    values:
      label: Gallery
      icon: collections
      value:
        heading:
        introduction_markdown:
        images:
  images:
    values:
      label: Image
      icon: image
      value:
        image:
        thumbnail:
        caption_text:
        alt_text:
  expandable-section:
    values:
      label: Expandable section
      icon: unfold_less
      value:
        header:
        content_markdown:
  scroll-section:
    values:
      label: Side navigation section
      icon: view_sidebar
      value:
        header:
        content_markdown:

_comments:
  thumbnail: A square image for the gallery's thumbnail
  slug: Shortened page URL
  caption_text: Optional text under the image
  alt_text: Describe the image for a screen reader