title: St. Invicta's Primary School
description: St. Invicta's is a primary school in Eastbourne, East Sussex.
image: /assets/images/classroom2.jpg
permalink: pretty
lang: en_GB


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  governors:
  teachers:
  about:
    _hide_content: true
    output: true
    permalink: /about/:title/

page_blocks: []
_array_structures:
  style: modal
  page_blocks:
    - label: Introduction Text
      icon: text
      value:
        _id: introduction_text
        content_markdown:
    - label: Text Block
      icon: content
      value:
        _id: text_block
        header:
        content_markdown:
    - label: Link Button
      icon: link
      value:
        _id: link_button
        link_text:
        link:

_options:
  content:
    uploads_dir: ":path"
    width: 200
    height: 300
    resize_style: "cover"
    expandable: true