title: St. Invicta's
description: St. Invicta's is a primary school in Eastbourne, East Sussex.
image: /assets/images/classroom2.jpg
permalink: pretty
locale: en_UK


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  - governors
  - teachers