title: St. Invicta's Primary School
description: St. Invicta's is a primary school in Eastbourne, East Sussex.
image: /assets/images/classroom2.jpg
permalink: pretty
lang: en_GB
timezone: Europe/London

url: https://puny-caribou.cloudvent.net

uploads_dir: "/assets/images/:title"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  governors:
  teachers:
  about:
    _hide_content: true
    output: true
    permalink: /about/:title/
  school-life:
    _hide_content: true
    output: true
    permalink: /school-life/:title/
  send:
    _hide_content: true
    output: true
    permalink: /send/:title/
  sen-policies:
    _hide_content: true
    output: true
    permalink: /send/sen-policies/:title/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title/


page_blocks: []
_array_structures:
  style: modal
  page_blocks:
    - label: Introduction Text
      icon: text
      value:
        _id: introduction_text
        content_markdown:
    - label: Text Block
      icon: content
      value:
        _id: text_block
        header:
        content_markdown:
    - label: Link Button
      icon: link
      value:
        _id: link_button
        link_text:
        link:


_options:
  content:
    height: 400
    width: 500
    resize_style: "cover"
  _block:
    format: p h1 h2 h3 h4 h5 h6 pre address
    bold: true
    italic: true
    removeformat: true
    link: true
    underline: true
    bulletedlist: true
    numberedlist: true
    table: true
    right: text-right
    # styles: /_sass/_content-typography.scss
    embed: true
    undo: true
    redo: true
    image: true