title: St. Invicta's Primary School
description: St. Invicta's is a primary school in Eastbourne, East Sussex.
image: /assets/images/classroom2.jpg
permalink: pretty
lang: en_GB
timezone: Europe/London

url: https://puny-caribou.cloudvent.net


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

uploads_dir: "/assets/media/:title"

# incremental: true

collections:
  governors:
    _hide_content: true
  teachers:
  school-information:
    _hide_content: true
    output: true
    permalink: /school-information/:title/
  school-life:
    _hide_content: true
    output: true
    permalink: /school-life/:title/
  send:
    _hide_content: true
    output: true
    permalink: /send/:title/
  sen-policies:
    _hide_content: true
    output: true
    permalink: /send/sen-policies/:title/
  staff:
    _hide_content: true
    output: true
    permalink: /staff/:title/
  policies:
    _hide_content: true
    output: true
    permalink: /policies/:title/
  posts:
    output: true
    permalink: /news/:year/:month/:day/:title/


page_blocks: []
_array_structures:
  style: modal
  page_blocks:
    - label: Introduction Text
      icon: text
      value:
        _id: introduction_text
        content_markdown:
    - label: Text Block
      icon: content
      value:
        _id: text_block
        header:
        content_markdown:
    - label: Link Button
      icon: link
      value:
        _id: link_button
        link_text:
        link:


_options:

  layout:
    hidden: true
  _block:
    height: 450
    width: 550
    resize_style: "cover"
    format: p h3 h4 h5
    bold: true
    italic: true
    removeformat: true
    link: true
    underline: true
    bulletedlist: true
    numberedlist: true
    table: true
    left: text-left
    center: text-center
    right: text-right
    justify: text-justify
    # styles: /_sass/_content-typography.scss
    embed: true
    undo: true
    redo: true
    image: true
  content:
    height: 450
    width: 550
    resize_style: "cover"
    format: p h3 h4 h5
    bold: true
    italic: true
    removeformat: true
    link: true
    underline: true
    bulletedlist: true
    numberedlist: true
    table: false
    # styles: /_sass/_content-typography.scss
    embed: true
    undo: true
    redo: true
    image: true