title: St. Invicta's
description: St. Invicta's is a primary school in Eastbourne, East Sussex.
cover image: /assets/images/
permalink: pretty


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  - governors
  - teachers