title: St. Invicta's Primary School
description: St. Invicta's is a primary school in Eastbourne, East Sussex.
permalink: pretty
lang: en_GB
timezone: Europe/London

url:

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

uploads_dir: "/assets/media/:title"

# incremental: true

collections:
  alerts:
    _hide_content: false
    output: true
    _icon: warning
  curriculum:
    _hide_content: false
    output: true
    permalink: /school-life/curriculum/:title/
    _add_options:
      - name: Add standard page
        icon: web
        href: ":_curriculum/.md🆕/_templates/_standard-page.md"
  school-information:
    _hide_content: false
    output: true
    permalink: /school-information/:title/
  school-life:
    _hide_content: false
    output: true
    permalink: /school-life/:title/
  send:
    _hide_content: false
    output: true
    permalink: /send/:title/
  sen-policies:
    _hide_content: false
    output: true
    permalink: /send/sen-policies/:title/
  staff:
    _hide_content: false
    output: true
    permalink: /staff/:title/
  policies:
    _hide_content: false
    output: true
    permalink: /policies/:title/
  posts:
    _enabled_editors:
      - content
      - visual
    output: true
    permalink: /news/:year/:month/:day/:title/

_options:

  layout:
    hidden: true
  _block:
    height: 500
    width: 800
    resize_style: "cover"
    format: p h3 h4 h5
    bold: true
    italic: true
    removeformat: true
    link: true
    underline: true
    blockquote: true
    bulletedlist: true
    numberedlist: true
    table: true
    left: text-left
    center: text-center
    right: text-right
    justify: false
    styles: /_sass/cms_styles.css
    embed: true
    undo: true
    redo: true
    image: true
  content:
    height: 500
    width: 800
    resize_style: "cover"
    format: p h3 h4 h5
    bold: true
    italic: true
    removeformat: true
    link: true
    underline: true
    blockquote: true
    bulletedlist: true
    numberedlist: true
    table: true
    left: text-left
    center: text-center
    right: text-right
    justify: false
    styles: /_sass/cms_styles.css
    embed: true
    undo: true
    redo: true
    image: true
  content_markdown:
    height: 500
    width: 800
    resize_style: "cover"
    format: p h3 h4 h5
    bold: true
    italic: true
    removeformat: true
    link: true
    underline: true
    blockquote: true
    bulletedlist: true
    numberedlist: true
    table: true
    left: text-left
    center: text-center
    right: text-right
    justify: false
    styles: /_sass/cms_styles.css
    embed: true
    undo: true
    redo: true
    image: true

_array_structures:
  gallery:
    values:
      label: Gallery
      icon: collections
      value:
        heading:
        introduction_markdown:
        images:
          - image:
            square-thumbnail:
            caption_text:
            alt_text:
