title: St. Invicta's Primary School
description: St. Invicta's is a primary school in Eastbourne, East Sussex.
image: /assets/images/classroom2.jpg
permalink: pretty
lang: en_GB


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

collections:
  - governors
  - teachers
  - about-page-links